// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"UserCode/PvPInstance.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/BrowseEvents.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/NowReportingScreen.lsml.js\"></script>");
