//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 3/6/2016 10:25:17 AM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for EventScores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EventScore> EventScores
        {
            get
            {
                if ((this._EventScores == null))
                {
                    this._EventScores = base.CreateQuery<EventScore>("EventScores");
                }
                return this._EventScores;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EventScore> _EventScores;
        /// <summary>
        /// There are no comments for EventSliceSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EventSlice> EventSliceSet
        {
            get
            {
                if ((this._EventSliceSet == null))
                {
                    this._EventSliceSet = base.CreateQuery<EventSlice>("EventSliceSet");
                }
                return this._EventSliceSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EventSlice> _EventSliceSet;
        /// <summary>
        /// There are no comments for PvPEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PvPEvent> PvPEvents
        {
            get
            {
                if ((this._PvPEvents == null))
                {
                    this._PvPEvents = base.CreateQuery<PvPEvent>("PvPEvents");
                }
                return this._PvPEvents;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PvPEvent> _PvPEvents;
        /// <summary>
        /// There are no comments for PvPInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PvPInstance> PvPInstances
        {
            get
            {
                if ((this._PvPInstances == null))
                {
                    this._PvPInstances = base.CreateQuery<PvPInstance>("PvPInstances");
                }
                return this._PvPInstances;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PvPInstance> _PvPInstances;
        /// <summary>
        /// There are no comments for EventScores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEventScores(EventScore eventScore)
        {
            base.AddObject("EventScores", eventScore);
        }
        /// <summary>
        /// There are no comments for EventSliceSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEventSliceSet(EventSlice eventSlice)
        {
            base.AddObject("EventSliceSet", eventSlice);
        }
        /// <summary>
        /// There are no comments for PvPEvents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPvPEvents(PvPEvent pvPEvent)
        {
            base.AddObject("PvPEvents", pvPEvent);
        }
        /// <summary>
        /// There are no comments for PvPInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPvPInstances(PvPInstance pvPInstance)
        {
            base.AddObject("PvPInstances", pvPInstance);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"EventScore\"><Key><PropertyRef Name=\"Id\" /></Ke" +
                "y><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGenerate" +
                "dPattern=\"Identity\" /><Property Name=\"Score\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
                "><Property Name=\"Rank\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Event" +
                "Score_EventSlice\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ScreenName" +
                "\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"CreatedBy\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Prope" +
                "rty Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modifi" +
                "ed\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nu" +
                "llable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Compute" +
                "d\" /><NavigationProperty Name=\"EventSlice\" Relationship=\"LightSwitchApplication." +
                "EventScore_EventSlice\" ToRole=\"EventSlice\" FromRole=\"EventScore\" /></EntityType>" +
                "<EntityType Name=\"EventSlice\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name" +
                "=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identi" +
                "ty\" /><Property Name=\"EventSlice_PvPInstance\" Type=\"Edm.Int32\" Nullable=\"false\" " +
                "/><Property Name=\"SliceNumber\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Nam" +
                "e=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=" +
                "\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"" +
                "255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"Row" +
                "Version\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:S" +
                "toreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"PvPInstance\" Relatio" +
                "nship=\"LightSwitchApplication.EventSlice_PvPInstance\" ToRole=\"PvPInstance\" FromR" +
                "ole=\"EventSlice\" /><NavigationProperty Name=\"EventScores\" Relationship=\"LightSwi" +
                "tchApplication.EventScore_EventSlice\" ToRole=\"EventScore\" FromRole=\"EventSlice\" " +
                "/></EntityType><EntityType Name=\"PvPEvent\"><Key><PropertyRef Name=\"Id\" /></Key><" +
                "Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPa" +
                "ttern=\"Identity\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxL" +
                "ength=\"255\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Pr" +
                "operty Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOf" +
                "fset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" Concurren" +
                "cyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /><NavigationProperty" +
                " Name=\"PvPInstances\" Relationship=\"LightSwitchApplication.PvPInstance_PvPEvent\" " +
                "ToRole=\"PvPInstance\" FromRole=\"PvPEvent\" /></EntityType><EntityType Name=\"PvPIns" +
                "tance\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" " +
                "Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"P" +
                "vPInstance_PvPEvent\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"StartTi" +
                "me\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Duration\" Type=\"Edm.D" +
                "ateTimeOffset\" Nullable=\"false\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" M" +
                "axLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property " +
                "Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" " +
                "Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullab" +
                "le=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /" +
                "><NavigationProperty Name=\"PvPEvent\" Relationship=\"LightSwitchApplication.PvPIns" +
                "tance_PvPEvent\" ToRole=\"PvPEvent\" FromRole=\"PvPInstance\" /><NavigationProperty N" +
                "ame=\"EventSliceCollection\" Relationship=\"LightSwitchApplication.EventSlice_PvPIn" +
                "stance\" ToRole=\"EventSlice\" FromRole=\"PvPInstance\" /></EntityType><Association N" +
                "ame=\"EventScore_EventSlice\"><End Role=\"EventSlice\" Type=\"LightSwitchApplication." +
                "EventSlice\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Role=\"Event" +
                "Score\" Type=\"LightSwitchApplication.EventScore\" Multiplicity=\"*\" /><ReferentialC" +
                "onstraint><Principal Role=\"EventSlice\"><PropertyRef Name=\"Id\" /></Principal><Dep" +
                "endent Role=\"EventScore\"><PropertyRef Name=\"EventScore_EventSlice\" /></Dependent" +
                "></ReferentialConstraint></Association><Association Name=\"PvPInstance_PvPEvent\">" +
                "<End Role=\"PvPEvent\" Type=\"LightSwitchApplication.PvPEvent\" Multiplicity=\"1\"><On" +
                "Delete Action=\"Cascade\" /></End><End Role=\"PvPInstance\" Type=\"LightSwitchApplica" +
                "tion.PvPInstance\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"PvP" +
                "Event\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"PvPInstance\"><Prope" +
                "rtyRef Name=\"PvPInstance_PvPEvent\" /></Dependent></ReferentialConstraint></Assoc" +
                "iation><Association Name=\"EventSlice_PvPInstance\"><End Role=\"PvPInstance\" Type=\"" +
                "LightSwitchApplication.PvPInstance\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" " +
                "/></End><End Role=\"EventSlice\" Type=\"LightSwitchApplication.EventSlice\" Multipli" +
                "city=\"*\" /><ReferentialConstraint><Principal Role=\"PvPInstance\"><PropertyRef Nam" +
                "e=\"Id\" /></Principal><Dependent Role=\"EventSlice\"><PropertyRef Name=\"EventSlice_" +
                "PvPInstance\" /></Dependent></ReferentialConstraint></Association><EntityContaine" +
                "r Name=\"ApplicationData\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Even" +
                "tScores\" EntityType=\"LightSwitchApplication.EventScore\" /><EntitySet Name=\"Event" +
                "SliceSet\" EntityType=\"LightSwitchApplication.EventSlice\" /><EntitySet Name=\"PvPE" +
                "vents\" EntityType=\"LightSwitchApplication.PvPEvent\" /><EntitySet Name=\"PvPInstan" +
                "ces\" EntityType=\"LightSwitchApplication.PvPInstance\" /><AssociationSet Name=\"Eve" +
                "ntScore_EventSlice\" Association=\"LightSwitchApplication.EventScore_EventSlice\"><" +
                "End Role=\"EventSlice\" EntitySet=\"EventSliceSet\" /><End Role=\"EventScore\" EntityS" +
                "et=\"EventScores\" /></AssociationSet><AssociationSet Name=\"PvPInstance_PvPEvent\" " +
                "Association=\"LightSwitchApplication.PvPInstance_PvPEvent\"><End Role=\"PvPEvent\" E" +
                "ntitySet=\"PvPEvents\" /><End Role=\"PvPInstance\" EntitySet=\"PvPInstances\" /></Asso" +
                "ciationSet><AssociationSet Name=\"EventSlice_PvPInstance\" Association=\"LightSwitc" +
                "hApplication.EventSlice_PvPInstance\"><End Role=\"PvPInstance\" EntitySet=\"PvPInsta" +
                "nces\" /><End Role=\"EventSlice\" EntitySet=\"EventSliceSet\" /></AssociationSet><Fun" +
                "ctionImport Name=\"NowReporting\" ReturnType=\"Collection(LightSwitchApplication.Pv" +
                "PInstance)\" EntitySet=\"PvPInstances\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"" +
                "Microsoft_LightSwitch_GetCanInformation\" ReturnType=\"Edm.String\" m:HttpMethod=\"G" +
                "ET\"><Parameter Name=\"dataServiceMembers\" Type=\"Edm.String\" Mode=\"In\" /></Functio" +
                "nImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.EventScore in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EventScores")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EventScore : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EventScore object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="score">Initial value of Score.</param>
        /// <param name="rank">Initial value of Rank.</param>
        /// <param name="eventScore_EventSlice">Initial value of EventScore_EventSlice.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EventScore CreateEventScore(int ID, int score, int rank, int eventScore_EventSlice, byte[] rowVersion)
        {
            EventScore eventScore = new EventScore();
            eventScore.Id = ID;
            eventScore.Score = score;
            eventScore.Rank = rank;
            eventScore.EventScore_EventSlice = eventScore_EventSlice;
            eventScore.RowVersion = rowVersion;
            return eventScore;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Score in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Score
        {
            get
            {
                return this._Score;
            }
            set
            {
                this.OnScoreChanging(value);
                if (object.Equals(this.Score, value))
                {
                    return;
                }
                this._Score = value;
                this.OnScoreChanged();
                this.OnPropertyChanged("Score");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Score;
        partial void OnScoreChanging(int value);
        partial void OnScoreChanged();
        /// <summary>
        /// There are no comments for Property Rank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Rank
        {
            get
            {
                return this._Rank;
            }
            set
            {
                this.OnRankChanging(value);
                if (object.Equals(this.Rank, value))
                {
                    return;
                }
                this._Rank = value;
                this.OnRankChanged();
                this.OnPropertyChanged("Rank");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Rank;
        partial void OnRankChanging(int value);
        partial void OnRankChanged();
        /// <summary>
        /// There are no comments for Property EventScore_EventSlice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventScore_EventSlice
        {
            get
            {
                return this._EventScore_EventSlice;
            }
            set
            {
                this.OnEventScore_EventSliceChanging(value);
                if (object.Equals(this.EventScore_EventSlice, value))
                {
                    return;
                }
                this._EventScore_EventSlice = value;
                this.OnEventScore_EventSliceChanged();
                this.OnPropertyChanged("EventScore_EventSlice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventScore_EventSlice;
        partial void OnEventScore_EventSliceChanging(int value);
        partial void OnEventScore_EventSliceChanged();
        /// <summary>
        /// There are no comments for Property ScreenName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ScreenName
        {
            get
            {
                return this._ScreenName;
            }
            set
            {
                this.OnScreenNameChanging(value);
                if (object.Equals(this.ScreenName, value))
                {
                    return;
                }
                this._ScreenName = value;
                this.OnScreenNameChanged();
                this.OnPropertyChanged("ScreenName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ScreenName;
        partial void OnScreenNameChanging(string value);
        partial void OnScreenNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for EventSlice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public EventSlice EventSlice
        {
            get
            {
                this.@__EventSlice.EnsureValueInitialized();
                return this._EventSlice;
            }
            set
            {
                EventSlice previous = this.EventSlice;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._EventSlice = null;
                    this.@__EventSlice.OnValueSet();
                    previous.EventScores.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.EventScore_EventSlice = value.Id;
                    }
                    else
                    {
                        this.EventScore_EventSlice = default(int);
                    }
                }
                this._EventSlice = value;
                this.@__EventSlice.OnValueSet();
                if ((value != null))
                {
                    value.@__EventScores.Add(this);
                }
                this.___OnPropertyChanged("EventSlice");
                this.OnPropertyChanged("EventSlice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private EventSlice _EventSlice;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.EventSlice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EventSliceSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EventSlice : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EventSlice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="eventSlice_PvPInstance">Initial value of EventSlice_PvPInstance.</param>
        /// <param name="sliceNumber">Initial value of SliceNumber.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EventSlice CreateEventSlice(int ID, int eventSlice_PvPInstance, int sliceNumber, byte[] rowVersion)
        {
            EventSlice eventSlice = new EventSlice();
            eventSlice.Id = ID;
            eventSlice.EventSlice_PvPInstance = eventSlice_PvPInstance;
            eventSlice.SliceNumber = sliceNumber;
            eventSlice.RowVersion = rowVersion;
            return eventSlice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property EventSlice_PvPInstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventSlice_PvPInstance
        {
            get
            {
                return this._EventSlice_PvPInstance;
            }
            set
            {
                this.OnEventSlice_PvPInstanceChanging(value);
                if (object.Equals(this.EventSlice_PvPInstance, value))
                {
                    return;
                }
                this._EventSlice_PvPInstance = value;
                this.OnEventSlice_PvPInstanceChanged();
                this.OnPropertyChanged("EventSlice_PvPInstance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventSlice_PvPInstance;
        partial void OnEventSlice_PvPInstanceChanging(int value);
        partial void OnEventSlice_PvPInstanceChanged();
        /// <summary>
        /// There are no comments for Property SliceNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SliceNumber
        {
            get
            {
                return this._SliceNumber;
            }
            set
            {
                this.OnSliceNumberChanging(value);
                if (object.Equals(this.SliceNumber, value))
                {
                    return;
                }
                this._SliceNumber = value;
                this.OnSliceNumberChanged();
                this.OnPropertyChanged("SliceNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SliceNumber;
        partial void OnSliceNumberChanging(int value);
        partial void OnSliceNumberChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for PvPInstance in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PvPInstance PvPInstance
        {
            get
            {
                this.@__PvPInstance.EnsureValueInitialized();
                return this._PvPInstance;
            }
            set
            {
                PvPInstance previous = this.PvPInstance;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._PvPInstance = null;
                    this.@__PvPInstance.OnValueSet();
                    previous.EventSliceCollection.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.EventSlice_PvPInstance = value.Id;
                    }
                    else
                    {
                        this.EventSlice_PvPInstance = default(int);
                    }
                }
                this._PvPInstance = value;
                this.@__PvPInstance.OnValueSet();
                if ((value != null))
                {
                    value.@__EventSliceCollection.Add(this);
                }
                this.___OnPropertyChanged("PvPInstance");
                this.OnPropertyChanged("PvPInstance");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PvPInstance _PvPInstance;
        /// <summary>
        /// There are no comments for EventScores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EventScore> EventScores
        {
            get
            {
                this.@__EventScores.EnsureValueInitialized();
                return this._EventScores;
            }
            set
            {
                this._EventScores = value;
                this.OnPropertyChanged("EventScores");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EventScore> _EventScores = new global::System.Data.Services.Client.DataServiceCollection<EventScore>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.PvPEvent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PvPEvents")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PvPEvent : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PvPEvent object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PvPEvent CreatePvPEvent(int ID, string name, byte[] rowVersion)
        {
            PvPEvent pvPEvent = new PvPEvent();
            pvPEvent.Id = ID;
            pvPEvent.Name = name;
            pvPEvent.RowVersion = rowVersion;
            return pvPEvent;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for PvPInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PvPInstance> PvPInstances
        {
            get
            {
                this.@__PvPInstances.EnsureValueInitialized();
                return this._PvPInstances;
            }
            set
            {
                this._PvPInstances = value;
                this.OnPropertyChanged("PvPInstances");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PvPInstance> _PvPInstances = new global::System.Data.Services.Client.DataServiceCollection<PvPInstance>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.PvPInstance in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PvPInstances")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PvPInstance : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PvPInstance object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="pvPInstance_PvPEvent">Initial value of PvPInstance_PvPEvent.</param>
        /// <param name="startTime">Initial value of StartTime.</param>
        /// <param name="duration">Initial value of Duration.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PvPInstance CreatePvPInstance(int ID, int pvPInstance_PvPEvent, global::System.DateTime startTime, global::System.DateTimeOffset duration, byte[] rowVersion)
        {
            PvPInstance pvPInstance = new PvPInstance();
            pvPInstance.Id = ID;
            pvPInstance.PvPInstance_PvPEvent = pvPInstance_PvPEvent;
            pvPInstance.StartTime = startTime;
            pvPInstance.Duration = duration;
            pvPInstance.RowVersion = rowVersion;
            return pvPInstance;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property PvPInstance_PvPEvent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PvPInstance_PvPEvent
        {
            get
            {
                return this._PvPInstance_PvPEvent;
            }
            set
            {
                this.OnPvPInstance_PvPEventChanging(value);
                if (object.Equals(this.PvPInstance_PvPEvent, value))
                {
                    return;
                }
                this._PvPInstance_PvPEvent = value;
                this.OnPvPInstance_PvPEventChanged();
                this.OnPropertyChanged("PvPInstance_PvPEvent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PvPInstance_PvPEvent;
        partial void OnPvPInstance_PvPEventChanging(int value);
        partial void OnPvPInstance_PvPEventChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                if (object.Equals(this.StartTime, value))
                {
                    return;
                }
                this._StartTime = value;
                this.OnStartTimeChanged();
                this.OnPropertyChanged("StartTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                if (object.Equals(this.Duration, value))
                {
                    return;
                }
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Duration;
        partial void OnDurationChanging(global::System.DateTimeOffset value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for PvPEvent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PvPEvent PvPEvent
        {
            get
            {
                this.@__PvPEvent.EnsureValueInitialized();
                return this._PvPEvent;
            }
            set
            {
                PvPEvent previous = this.PvPEvent;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._PvPEvent = null;
                    this.@__PvPEvent.OnValueSet();
                    previous.PvPInstances.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.PvPInstance_PvPEvent = value.Id;
                    }
                    else
                    {
                        this.PvPInstance_PvPEvent = default(int);
                    }
                }
                this._PvPEvent = value;
                this.@__PvPEvent.OnValueSet();
                if ((value != null))
                {
                    value.@__PvPInstances.Add(this);
                }
                this.___OnPropertyChanged("PvPEvent");
                this.OnPropertyChanged("PvPEvent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PvPEvent _PvPEvent;
        /// <summary>
        /// There are no comments for EventSliceCollection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EventSlice> EventSliceCollection
        {
            get
            {
                this.@__EventSliceCollection.EnsureValueInitialized();
                return this._EventSliceCollection;
            }
            set
            {
                this._EventSliceCollection = value;
                this.OnPropertyChanged("EventSliceCollection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EventSlice> _EventSliceCollection = new global::System.Data.Services.Client.DataServiceCollection<EventSlice>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
