//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region EventScore
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EventScore :
        global::LightSwitchApplication.EventScore.DetailsClass.IImplementation
    {
        partial void OnEventScore_EventSliceChanged()
        {
            this.___OnPropertyChanged("EventScore_EventSlice");
            this.___OnPropertyChanged("EventSlice");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnScoreChanged()
        {
            this.___OnPropertyChanged("Score");
        }
        
        partial void OnRankChanged()
        {
            this.___OnPropertyChanged("Rank");
        }
        
        partial void OnScreenNameChanged()
        {
            this.___OnPropertyChanged("ScreenName");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EventScore.DetailsClass.IImplementation.EventSlice
        {
            get
            {
                return this.EventSlice;
            }
            set
            {
                this.EventSlice = (global::LightSwitchApplication.Implementation.EventSlice)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EventSlice> __EventSlice
        {
            get
            {
                if (this.___EventSlice == null)
                {
                    this.___EventSlice = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EventSlice>(
                        this,
                        "EventSlice",
                        new string[] { "EventScore_EventSlice" },
                        e => global::System.Object.Equals(e.Id, this.EventScore_EventSlice),
                        () => this._EventSlice,
                        e => this._EventSlice = e);
                }
                return this.___EventSlice;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EventSlice> ___EventSlice;
        
    }
    #endregion
    
    #region EventSlice
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EventSlice :
        global::LightSwitchApplication.EventSlice.DetailsClass.IImplementation
    {
        partial void OnEventSlice_PvPInstanceChanged()
        {
            this.___OnPropertyChanged("EventSlice_PvPInstance");
            this.___OnPropertyChanged("PvPInstance");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnSliceNumberChanged()
        {
            this.___OnPropertyChanged("SliceNumber");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EventSlice.DetailsClass.IImplementation.PvPInstance
        {
            get
            {
                return this.PvPInstance;
            }
            set
            {
                this.PvPInstance = (global::LightSwitchApplication.Implementation.PvPInstance)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PvPInstance> __PvPInstance
        {
            get
            {
                if (this.___PvPInstance == null)
                {
                    this.___PvPInstance = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PvPInstance>(
                        this,
                        "PvPInstance",
                        new string[] { "EventSlice_PvPInstance" },
                        e => global::System.Object.Equals(e.Id, this.EventSlice_PvPInstance),
                        () => this._PvPInstance,
                        e => this._PvPInstance = e);
                }
                return this.___PvPInstance;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PvPInstance> ___PvPInstance;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EventSlice.DetailsClass.IImplementation.EventScores
        {
            get
            {
                return this.EventScores;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventScore> __EventScores
        {
            get
            {
                if (this.___EventScores == null)
                {
                    this.___EventScores = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventScore>(
                        this,
                        "EventScores",
                        () => this._EventScores,
                        e => global::System.Object.Equals(e.EventScore_EventSlice, this.Id));
                }
                return this.___EventScores;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventScore> ___EventScores;
        
    }
    #endregion
    
    #region PvPEvent
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PvPEvent :
        global::LightSwitchApplication.PvPEvent.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.PvPEvent.DetailsClass.IImplementation.PvPInstances
        {
            get
            {
                return this.PvPInstances;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PvPInstance> __PvPInstances
        {
            get
            {
                if (this.___PvPInstances == null)
                {
                    this.___PvPInstances = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PvPInstance>(
                        this,
                        "PvPInstances",
                        () => this._PvPInstances,
                        e => global::System.Object.Equals(e.PvPInstance_PvPEvent, this.Id));
                }
                return this.___PvPInstances;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.PvPInstance> ___PvPInstances;
        
    }
    #endregion
    
    #region PvPInstance
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class PvPInstance :
        global::LightSwitchApplication.PvPInstance.DetailsClass.IImplementation
    {
        partial void OnPvPInstance_PvPEventChanged()
        {
            this.___OnPropertyChanged("PvPInstance_PvPEvent");
            this.___OnPropertyChanged("PvPEvent");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStartTimeChanged()
        {
            this.___OnPropertyChanged("StartTime");
        }
        
        partial void OnDurationChanged()
        {
            this.___OnPropertyChanged("Duration");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.PvPInstance.DetailsClass.IImplementation.PvPEvent
        {
            get
            {
                return this.PvPEvent;
            }
            set
            {
                this.PvPEvent = (global::LightSwitchApplication.Implementation.PvPEvent)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PvPEvent> __PvPEvent
        {
            get
            {
                if (this.___PvPEvent == null)
                {
                    this.___PvPEvent = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PvPEvent>(
                        this,
                        "PvPEvent",
                        new string[] { "PvPInstance_PvPEvent" },
                        e => global::System.Object.Equals(e.Id, this.PvPInstance_PvPEvent),
                        () => this._PvPEvent,
                        e => this._PvPEvent = e);
                }
                return this.___PvPEvent;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.PvPEvent> ___PvPEvent;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.PvPInstance.DetailsClass.IImplementation.EventSliceCollection
        {
            get
            {
                return this.EventSliceCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventSlice> __EventSliceCollection
        {
            get
            {
                if (this.___EventSliceCollection == null)
                {
                    this.___EventSliceCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventSlice>(
                        this,
                        "EventSliceCollection",
                        () => this._EventSliceCollection,
                        e => global::System.Object.Equals(e.EventSlice_PvPInstance, this.Id));
                }
                return this.___EventSliceCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EventSlice> ___EventSliceCollection;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.EventScore))
            {
                return new global::LightSwitchApplication.Implementation.EventScore();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EventSlice))
            {
                return new global::LightSwitchApplication.Implementation.EventSlice();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PvPEvent))
            {
                return new global::LightSwitchApplication.Implementation.PvPEvent();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.PvPInstance))
            {
                return new global::LightSwitchApplication.Implementation.PvPInstance();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.EventScore) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EventScore);
            }
            if (typeof(global::LightSwitchApplication.EventSlice) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EventSlice);
            }
            if (typeof(global::LightSwitchApplication.PvPEvent) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PvPEvent);
            }
            if (typeof(global::LightSwitchApplication.PvPInstance) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.PvPInstance);
            }
            return null;
        }
    }
}
