//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Inserting(global::LightSwitchApplication.EventScore entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Inserted(global::LightSwitchApplication.EventScore entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Updating(global::LightSwitchApplication.EventScore entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Updated(global::LightSwitchApplication.EventScore entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Deleting(global::LightSwitchApplication.EventScore entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Deleted(global::LightSwitchApplication.EventScore entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Validate(global::LightSwitchApplication.EventScore entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventScores_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventScore, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Inserting(global::LightSwitchApplication.EventSlice entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Inserted(global::LightSwitchApplication.EventSlice entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Updating(global::LightSwitchApplication.EventSlice entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Updated(global::LightSwitchApplication.EventSlice entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Deleting(global::LightSwitchApplication.EventSlice entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Deleted(global::LightSwitchApplication.EventSlice entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Validate(global::LightSwitchApplication.EventSlice entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSliceSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventSlice, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Inserting(global::LightSwitchApplication.PvPEvent entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Inserted(global::LightSwitchApplication.PvPEvent entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Updating(global::LightSwitchApplication.PvPEvent entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Updated(global::LightSwitchApplication.PvPEvent entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Deleting(global::LightSwitchApplication.PvPEvent entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Deleted(global::LightSwitchApplication.PvPEvent entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Validate(global::LightSwitchApplication.PvPEvent entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvents_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PvPEvent, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Inserting(global::LightSwitchApplication.PvPInstance entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Inserted(global::LightSwitchApplication.PvPInstance entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Updating(global::LightSwitchApplication.PvPInstance entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Updated(global::LightSwitchApplication.PvPInstance entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Deleting(global::LightSwitchApplication.PvPInstance entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Deleted(global::LightSwitchApplication.PvPInstance entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Validate(global::LightSwitchApplication.PvPInstance entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstances_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PvPInstance, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.EventScore>
                __EventScoresEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.EventScore>(
                    "EventScores",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventScores_Filter);
            private static bool __EventScores_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventScores_CanInsert(ref result);
                return result;
            }
            private static bool __EventScores_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventScores_CanUpdate(ref result);
                return result;
            }
            private static bool __EventScores_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventScores_CanDelete(ref result);
                return result;
            }
            private static bool __EventScores_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventScores_CanRead(ref result);
                return result;
            }
            private static void __EventScores_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e)
            {
                d.EventScores_Inserting(e);
            }
            private static void __EventScores_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e)
            {
                d.EventScores_Inserted(e);
            }
            private static void __EventScores_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e)
            {
                d.EventScores_Updating(e);
            }
            private static void __EventScores_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e)
            {
                d.EventScores_Updated(e);
            }
            private static void __EventScores_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e)
            {
                d.EventScores_Deleting(e);
            }
            private static void __EventScores_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e)
            {
                d.EventScores_Deleted(e);
            }
            private static void __EventScores_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventScore e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.EventScores_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventScore, bool>> __EventScores_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventScore, bool>> filter = null;
                d.EventScores_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.EventSlice>
                __EventSliceSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.EventSlice>(
                    "EventSliceSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EventSliceSet_Filter);
            private static bool __EventSliceSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventSliceSet_CanInsert(ref result);
                return result;
            }
            private static bool __EventSliceSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventSliceSet_CanUpdate(ref result);
                return result;
            }
            private static bool __EventSliceSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventSliceSet_CanDelete(ref result);
                return result;
            }
            private static bool __EventSliceSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.EventSliceSet_CanRead(ref result);
                return result;
            }
            private static void __EventSliceSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e)
            {
                d.EventSliceSet_Inserting(e);
            }
            private static void __EventSliceSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e)
            {
                d.EventSliceSet_Inserted(e);
            }
            private static void __EventSliceSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e)
            {
                d.EventSliceSet_Updating(e);
            }
            private static void __EventSliceSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e)
            {
                d.EventSliceSet_Updated(e);
            }
            private static void __EventSliceSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e)
            {
                d.EventSliceSet_Deleting(e);
            }
            private static void __EventSliceSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e)
            {
                d.EventSliceSet_Deleted(e);
            }
            private static void __EventSliceSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.EventSliceSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventSlice, bool>> __EventSliceSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.EventSlice, bool>> filter = null;
                d.EventSliceSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.PvPEvent>
                __PvPEventsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.PvPEvent>(
                    "PvPEvents",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPEvents_Filter);
            private static bool __PvPEvents_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPEvents_CanInsert(ref result);
                return result;
            }
            private static bool __PvPEvents_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPEvents_CanUpdate(ref result);
                return result;
            }
            private static bool __PvPEvents_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPEvents_CanDelete(ref result);
                return result;
            }
            private static bool __PvPEvents_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPEvents_CanRead(ref result);
                return result;
            }
            private static void __PvPEvents_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e)
            {
                d.PvPEvents_Inserting(e);
            }
            private static void __PvPEvents_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e)
            {
                d.PvPEvents_Inserted(e);
            }
            private static void __PvPEvents_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e)
            {
                d.PvPEvents_Updating(e);
            }
            private static void __PvPEvents_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e)
            {
                d.PvPEvents_Updated(e);
            }
            private static void __PvPEvents_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e)
            {
                d.PvPEvents_Deleting(e);
            }
            private static void __PvPEvents_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e)
            {
                d.PvPEvents_Deleted(e);
            }
            private static void __PvPEvents_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPEvent e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.PvPEvents_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PvPEvent, bool>> __PvPEvents_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PvPEvent, bool>> filter = null;
                d.PvPEvents_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.PvPInstance>
                __PvPInstancesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.PvPInstance>(
                    "PvPInstances",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__PvPInstances_Filter);
            private static bool __PvPInstances_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPInstances_CanInsert(ref result);
                return result;
            }
            private static bool __PvPInstances_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPInstances_CanUpdate(ref result);
                return result;
            }
            private static bool __PvPInstances_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPInstances_CanDelete(ref result);
                return result;
            }
            private static bool __PvPInstances_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.PvPInstances_CanRead(ref result);
                return result;
            }
            private static void __PvPInstances_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e)
            {
                d.PvPInstances_Inserting(e);
            }
            private static void __PvPInstances_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e)
            {
                d.PvPInstances_Inserted(e);
            }
            private static void __PvPInstances_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e)
            {
                d.PvPInstances_Updating(e);
            }
            private static void __PvPInstances_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e)
            {
                d.PvPInstances_Updated(e);
            }
            private static void __PvPInstances_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e)
            {
                d.PvPInstances_Deleting(e);
            }
            private static void __PvPInstances_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e)
            {
                d.PvPInstances_Deleted(e);
            }
            private static void __PvPInstances_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.PvPInstances_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PvPInstance, bool>> __PvPInstances_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.PvPInstance, bool>> filter = null;
                d.PvPInstances_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
