

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class EventSlice : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EventSlice entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EventSlice()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EventSlice(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EventSlice> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EventSlice.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSlice_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EventSlice_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.EventSlice.DetailsClass.SetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SliceNumber
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.SliceNumber);
            }
            set
            {
                global::LightSwitchApplication.EventSlice.DetailsClass.SetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.SliceNumber, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SliceNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SliceNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SliceNumber_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.EventSlice.DetailsClass.SetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.PvPInstance PvPInstance
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.PvPInstance);
            }
            set
            {
                global::LightSwitchApplication.EventSlice.DetailsClass.SetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.PvPInstance, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstance_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstance_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstance_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EventScore> EventScores
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetValue(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.EventScores);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EventScore> EventScoresQuery
        {
            get
            {
                return global::LightSwitchApplication.EventSlice.DetailsClass.GetQuery(this, global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.EventScores);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EventSlice,
                global::LightSwitchApplication.EventSlice.DetailsClass,
                global::LightSwitchApplication.EventSlice.DetailsClass.IImplementation,
                global::LightSwitchApplication.EventSlice.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>.Entry
                __EventSliceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>.Entry(
                    global::LightSwitchApplication.EventSlice.DetailsClass.__EventSlice_CreateNew,
                    global::LightSwitchApplication.EventSlice.DetailsClass.__EventSlice_Created,
                    global::LightSwitchApplication.EventSlice.DetailsClass.__EventSlice_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EventSlice __EventSlice_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EventSlice> es)
            {
                return new global::LightSwitchApplication.EventSlice(es);
            }
            private static void __EventSlice_Created(global::LightSwitchApplication.EventSlice e)
            {
                e.EventSlice_Created();
            }
            private static bool __EventSlice_AllowSaveWithErrors(global::LightSwitchApplication.EventSlice e)
            {
                bool result = false;
                e.EventSlice_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EventSlice.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int> SliceNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.SliceNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.PvPInstance> PvPInstance
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.PvPInstance) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.PvPInstance>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.EventScore> EventScores
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.EventScores) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.EventScore>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int SliceNumber { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation PvPInstance { get; set; }
                new global::System.Collections.IEnumerable EventScores { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Entry
                    SliceNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Entry(
                        "SliceNumber",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._SliceNumber_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._SliceNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._SliceNumber_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._SliceNumber_GetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._SliceNumber_SetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._SliceNumber_OnValueChanged);
                private static void _SliceNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._SliceNumber, sf);
                }
                private static bool _SliceNumber_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.SliceNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _SliceNumber_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SliceNumber_Validate(r);
                }
                private static int _SliceNumber_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.SliceNumber;
                }
                private static void _SliceNumber_SetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SliceNumber = v;
                }
                private static void _SliceNumber_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.SliceNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.PvPInstance>.Entry
                    PvPInstance = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.PvPInstance>.Entry(
                        "PvPInstance",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_ComputeIsReadOnly,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_Validate,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_GetCoreImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_GetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_SetImplementationValue,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_Refresh,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._PvPInstance_OnValueChanged);
                private static void _PvPInstance_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.PvPInstance>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._PvPInstance, sf);
                }
                private static bool _PvPInstance_ComputeIsReadOnly(global::LightSwitchApplication.EventSlice e)
                {
                    bool result = false;
                    e.PvPInstance_IsReadOnly(ref result);
                    return result;
                }
                private static void _PvPInstance_Validate(global::LightSwitchApplication.EventSlice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PvPInstance_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _PvPInstance_GetCoreImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.PvPInstance;
                }
                private static global::LightSwitchApplication.PvPInstance _PvPInstance_GetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.PvPInstance, ref d._PvPInstance);
                }
                private static void _PvPInstance_SetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass d, global::LightSwitchApplication.PvPInstance v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.PvPInstance, ref d._PvPInstance, (i, ev) => i.PvPInstance = ev, v);
                }
                private static void _PvPInstance_Refresh(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.PvPInstance, ref d._PvPInstance);
                }
                private static void _PvPInstance_OnValueChanged(global::LightSwitchApplication.EventSlice e)
                {
                    e.PvPInstance_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.EventScore>.Entry
                    EventScores = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.EventScore>.Entry(
                        "EventScores",
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._EventScores_Stub,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._EventScores_GetReferencedEntities,
                        global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties._EventScores_GetEntityCollection);
                private static void _EventScores_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EventSlice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.EventScore>.Data> c, global::LightSwitchApplication.EventSlice.DetailsClass d, object sf)
                {
                    c(d, ref d._EventScores, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EventScore> _EventScores_GetReferencedEntities(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EventScore, global::LightSwitchApplication.EventScore.DetailsClass>(global::LightSwitchApplication.EventSlice.DetailsClass.PropertySetProperties.EventScores, ref d._EventScores);
                }
                private static global::System.Collections.IEnumerable _EventScores_GetEntityCollection(global::LightSwitchApplication.EventSlice.DetailsClass d)
                {
                    return d.ImplementationEntity.EventScores;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, int>.Data _SliceNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.PvPInstance>.Data _PvPInstance;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass, global::LightSwitchApplication.EventScore>.Data _EventScores;
            
        }
    
        #endregion
    }
    
    #endregion
}
