

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class PvPInstance : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PvPInstance entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PvPInstance()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PvPInstance(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PvPInstance> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PvPInstance.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstance_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPInstance_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.PvPInstance.DetailsClass.SetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.StartTime);
            }
            set
            {
                global::LightSwitchApplication.PvPInstance.DetailsClass.SetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.StartTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.EndTime);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndTime_Compute(ref global::System.DateTime result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTimeOffset Duration
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Duration);
            }
            set
            {
                global::LightSwitchApplication.PvPInstance.DetailsClass.SetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Duration, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Duration_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Duration_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Duration_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.PvPInstance.DetailsClass.SetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.PvPEvent PvPEvent
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.PvPEvent);
            }
            set
            {
                global::LightSwitchApplication.PvPInstance.DetailsClass.SetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.PvPEvent, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvent_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvent_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PvPEvent_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EventSlice> EventSliceCollection
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetValue(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.EventSliceCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EventSlice> EventSliceCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.PvPInstance.DetailsClass.GetQuery(this, global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.EventSliceCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PvPInstance,
                global::LightSwitchApplication.PvPInstance.DetailsClass,
                global::LightSwitchApplication.PvPInstance.DetailsClass.IImplementation,
                global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>.Entry
                __PvPInstanceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>.Entry(
                    global::LightSwitchApplication.PvPInstance.DetailsClass.__PvPInstance_CreateNew,
                    global::LightSwitchApplication.PvPInstance.DetailsClass.__PvPInstance_Created,
                    global::LightSwitchApplication.PvPInstance.DetailsClass.__PvPInstance_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PvPInstance __PvPInstance_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PvPInstance> es)
            {
                return new global::LightSwitchApplication.PvPInstance(es);
            }
            private static void __PvPInstance_Created(global::LightSwitchApplication.PvPInstance e)
            {
                e.PvPInstance_Created();
            }
            private static bool __PvPInstance_AllowSaveWithErrors(global::LightSwitchApplication.PvPInstance e)
            {
                bool result = false;
                e.PvPInstance_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime> StartTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.StartTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime> EndTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.EndTime) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTimeOffset> Duration
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Duration) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTimeOffset>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.PvPEvent> PvPEvent
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.PvPEvent) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.PvPEvent>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.EventSlice> EventSliceCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.EventSliceCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.EventSlice>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime StartTime { get; set; }
                new global::System.DateTimeOffset Duration { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation PvPEvent { get; set; }
                new global::System.Collections.IEnumerable EventSliceCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, int>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Entry
                    StartTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Entry(
                        "StartTime",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._StartTime_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._StartTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._StartTime_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._StartTime_GetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._StartTime_SetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._StartTime_OnValueChanged);
                private static void _StartTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._StartTime, sf);
                }
                private static bool _StartTime_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.StartTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _StartTime_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StartTime_Validate(r);
                }
                private static global::System.DateTime _StartTime_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.StartTime;
                }
                private static void _StartTime_SetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.StartTime = global::LightSwitchApplication.PvPInstance.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _StartTime_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.StartTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Entry
                    EndTime = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Entry(
                        "EndTime",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._EndTime_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._EndTime_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._EndTime_ComputeValue);
                private static void _EndTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._EndTime, sf);
                }
                private static void _EndTime_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EndTime_Validate(r);
                }
                private static global::System.DateTime _EndTime_ComputeValue(global::LightSwitchApplication.PvPInstance e)
                {
                    global::System.DateTime value = default(global::System.DateTime);
                    e.EndTime_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTimeOffset>.Entry
                    Duration = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTimeOffset>.Entry(
                        "Duration",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Duration_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Duration_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Duration_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Duration_GetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Duration_SetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Duration_OnValueChanged);
                private static void _Duration_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTimeOffset>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._Duration, sf);
                }
                private static bool _Duration_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.Duration_IsReadOnly(ref result);
                    return result;
                }
                private static void _Duration_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Duration_Validate(r);
                }
                private static global::System.DateTimeOffset _Duration_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.Duration;
                }
                private static void _Duration_SetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d, global::System.DateTimeOffset v)
                {
                    d.ImplementationEntity.Duration = v;
                }
                private static void _Duration_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.Duration_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.PvPEvent>.Entry
                    PvPEvent = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.PvPEvent>.Entry(
                        "PvPEvent",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_ComputeIsReadOnly,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_Validate,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_GetCoreImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_GetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_SetImplementationValue,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_Refresh,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._PvPEvent_OnValueChanged);
                private static void _PvPEvent_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.PvPEvent>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._PvPEvent, sf);
                }
                private static bool _PvPEvent_ComputeIsReadOnly(global::LightSwitchApplication.PvPInstance e)
                {
                    bool result = false;
                    e.PvPEvent_IsReadOnly(ref result);
                    return result;
                }
                private static void _PvPEvent_Validate(global::LightSwitchApplication.PvPInstance e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PvPEvent_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _PvPEvent_GetCoreImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.PvPEvent;
                }
                private static global::LightSwitchApplication.PvPEvent _PvPEvent_GetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.PvPEvent, global::LightSwitchApplication.PvPEvent.DetailsClass>(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.PvPEvent, ref d._PvPEvent);
                }
                private static void _PvPEvent_SetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass d, global::LightSwitchApplication.PvPEvent v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.PvPEvent, ref d._PvPEvent, (i, ev) => i.PvPEvent = ev, v);
                }
                private static void _PvPEvent_Refresh(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.PvPEvent, ref d._PvPEvent);
                }
                private static void _PvPEvent_OnValueChanged(global::LightSwitchApplication.PvPInstance e)
                {
                    e.PvPEvent_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.EventSlice>.Entry
                    EventSliceCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.EventSlice>.Entry(
                        "EventSliceCollection",
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._EventSliceCollection_Stub,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._EventSliceCollection_GetReferencedEntities,
                        global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties._EventSliceCollection_GetEntityCollection);
                private static void _EventSliceCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PvPInstance.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.EventSlice>.Data> c, global::LightSwitchApplication.PvPInstance.DetailsClass d, object sf)
                {
                    c(d, ref d._EventSliceCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EventSlice> _EventSliceCollection_GetReferencedEntities(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EventSlice, global::LightSwitchApplication.EventSlice.DetailsClass>(global::LightSwitchApplication.PvPInstance.DetailsClass.PropertySetProperties.EventSliceCollection, ref d._EventSliceCollection);
                }
                private static global::System.Collections.IEnumerable _EventSliceCollection_GetEntityCollection(global::LightSwitchApplication.PvPInstance.DetailsClass d)
                {
                    return d.ImplementationEntity.EventSliceCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Data _StartTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTime>.Data _EndTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.DateTimeOffset>.Data _Duration;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.PvPEvent>.Data _PvPEvent;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PvPInstance, global::LightSwitchApplication.PvPInstance.DetailsClass, global::LightSwitchApplication.EventSlice>.Data _EventSliceCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
